--create directory GJ as 'D:\NHIS_DATA\12.gj';

--declare idx number;


		create table NHID_GJ_2008_ext
			(HCHK_YEAR	VARCHAR2(4)
			,PERSON_ID	NUMBER(8)
			,YKIHO_GUBUN_CD	VARCHAR2(2)
			,HEIGHT	NUMBER(3)
			,WEIGHT	NUMBER(3)
			,WAIST	NUMBER(3)
			,BP_HIGH	NUMBER(3)
			,BP_LWST	NUMBER(3)
			,BLDS	NUMBER(3)
			,TOT_CHOLE	NUMBER(3)
			,TRIGLYCERIDE	NUMBER(3)
			,HDL_CHOLE	NUMBER(3)
			,LDL_CHOLE	NUMBER(3)
			,HMG	NUMBER(3)
			,GLY_CD	VARCHAR2(1)
			,OLIG_OCCU_CD	VARCHAR2(1)
			,OLIG_PH	NUMBER(3)
			,OLIG_PROTE_CD	VARCHAR2(1)
			,CREATININE	NUMBER(3)
			,SGOT_AST	NUMBER(3)
			,SGPT_ALT	NUMBER(3)
			,GAMMA_GTP	NUMBER(3)
			,HCHK_PMH_CD1	VARCHAR2(1)
			,HCHK_PMH_CD2	VARCHAR2(1)
			,HCHK_PMH_CD3	VARCHAR2(1)
			,FMLY_LIVER_DISE_PATIEN_YN	VARCHAR2(1)
			,FMLY_HPRTS_PATIEN_YN	VARCHAR2(1)
			,FMLY_APOP_PATIEN_YN	VARCHAR2(1)
			,FMLY_HDISE_PATIEN_YN	VARCHAR2(1)
			,FMLY_DIABML_PATIEN_YN	VARCHAR2(1)
			,FMLY_CANCER_PATIEN_YN	VARCHAR2(1)
			,SMK_STAT_TYPE_RSPS_CD	VARCHAR2(1)
			,SMK_TERM_RSPS_CD	VARCHAR2(1)
			,DSQTY_RSPS_CD	VARCHAR2(1)
			,DRNK_HABIT_RSPS_CD	VARCHAR2(1)
			,TM1_DRKQTY_RSPS_CD	VARCHAR2(1)
			,EXERCI_FREQ_RSPS_CD	VARCHAR2(1)
			)
			ORGANIZATION EXTERNAL
			(
			TYPE oracle_loader
			DEFAULT DIRECTORY GJ
			ACCESS PARAMETERS
			(
			RECORDS DELIMITED BY "\n"
			CHARACTERSET KO16KSC5601
			FIELDS TERMINATED BY "|" OPTIONALLY ENCLOSED BY '"' LRTRIM
			MISSING FIELD VALUES ARE NULL
			)
			LOCATION
			(
			'NHID_GJ_2008.TXT'
			)
			)REJECT LIMIT UNLIMITED;

begin
	for idx in 2002..2007
	loop
	execute immediate(
		'create table NHID_GJ_'||idx||'_ext
			(HCHK_YEAR	VARCHAR2(4)
			,PERSON_ID	NUMBER(8)
			,YKIHO_GUBUN_CD	VARCHAR2(2)
			,HEIGHT	NUMBER(3)
			,WEIGHT	NUMBER(3)
			,BP_HIGH	NUMBER(3)
			,BP_LWST	NUMBER(3)
			,BLDS	NUMBER(3)
			,TOT_CHOLE	NUMBER(3)
			,HMG	NUMBER(3)
			,GLY_CD	VARCHAR2(1)
			,OLIG_OCCU_CD	VARCHAR2(1)
			,OLIG_PH	NUMBER(3)
			,OLIG_PROTE_CD	VARCHAR2(1)
			,SGOT_AST	NUMBER(3)
			,SGPT_ALT	NUMBER(3)
			,GAMMA_GTP	NUMBER(3)
			,HCHK_PMH_CD1	VARCHAR2(1)
			,HCHK_PMH_CD2	VARCHAR2(1)
			,HCHK_PMH_CD3	VARCHAR2(1)
			,FMLY_LIVER_DISE_PATIEN_YN	VARCHAR2(1)
			,FMLY_HPRTS_PATIEN_YN	VARCHAR2(1)
			,FMLY_APOP_PATIEN_YN	VARCHAR2(1)
			,FMLY_HDISE_PATIEN_YN	VARCHAR2(1)
			,FMLY_DIABML_PATIEN_YN	VARCHAR2(1)
			,FMLY_CANCER_PATIEN_YN	VARCHAR2(1)
			,SMK_STAT_TYPE_RSPS_CD	VARCHAR2(1)
			,SMK_TERM_RSPS_CD	VARCHAR2(1)
			,DSQTY_RSPS_CD	VARCHAR2(1)
			,DRNK_HABIT_RSPS_CD	VARCHAR2(1)
			,TM1_DRKQTY_RSPS_CD	VARCHAR2(1)
			,EXERCI_FREQ_RSPS_CD	VARCHAR2(1)
			)
			ORGANIZATION EXTERNAL
			(
			TYPE oracle_loader
			DEFAULT DIRECTORY GJ
			ACCESS PARAMETERS
			(
			RECORDS DELIMITED BY ''\n''
			CHARACTERSET KO16KSC5601
			FIELDS TERMINATED BY ''|'' OPTIONALLY ENCLOSED BY ''"'' LRTRIM
			MISSING FIELD VALUES ARE NULL
			)
			LOCATION
			(
			''NHID_GJ_'||idx||'.TXT''
			)
			)REJECT LIMIT UNLIMITED');
		end loop;

		for idx in 2009..2013
		loop
		execute immediate(
		'create table NHID_GJ_'||idx||'_ext
			(HCHK_YEAR 				VARCHAR2(4)
			,PERSON_ID 				NUMBER(8)
			,YKIHO_GUBUN_CD 		VARCHAR2(2)
			,HEIGHT 				NUMBER(3)
			,WEIGHT 				NUMBER(3)
			,WAIST 					NUMBER(3)
			,BP_HIGH 				NUMBER(3)
			,BP_LWST 				NUMBER(3)
			,BLDS 					NUMBER(3)
			,TOT_CHOLE 				NUMBER(3)
			,TRIGLYCERIDE 			NUMBER(3)
			,HDL_CHOLE 				NUMBER(3)
			,LDL_CHOLE 				NUMBER(3)
			,HMG 					NUMBER(3)
			,OLIG_PROTE_CD 			VARCHAR2(1)
			,CREATININE 			NUMBER(3)
			,SGOT_AST 				NUMBER(3)
			,SGPT_ALT 				NUMBER(3)
			,GAMMA_GTP 				NUMBER(3)
			,HCHK_APOP_PMH_YN 		VARCHAR2(1)
			,HCHK_HDISE_PMH_YN 		VARCHAR2(1)
			,HCHK_HPRTS_PMH_YN 		VARCHAR2(1)
			,HCHK_DIABML_PMH_YN 	VARCHAR2(1)
			,HCHK_HPLPDM_PMH_YN 	VARCHAR2(1)
			,HCHK_PHSS_PMH_YN 		VARCHAR2(1)
			,HCHK_ETCDSE_PMH_YN 	VARCHAR2(1)
			,FMLY_APOP_PATIEN_YN 	VARCHAR2(1)
			,FMLY_HDISE_PATIEN_YN 	VARCHAR2(1)
			,FMLY_HPRTS_PATIEN_YN 	VARCHAR2(1)
			,FMLY_DIABML_PATIEN_YN 	VARCHAR2(1)
			,FMLY_CANCER_PATIEN_YN 	VARCHAR2(1)
			,SMK_STAT_TYPE_RSPS_CD 	VARCHAR2(1)
			,PAST_SMK_TERM_RSPS_CD 	NUMBER(3)
			,PAST_DSQTY_RSPS_CD 	NUMBER(3)
			,CUR_SMK_TERM_RSPS_CD 	NUMBER(3)
			,CUR_DSQTY_RSPS_CD 		NUMBER(3)
			,DRNK_HABIT_RSPS_CD 	VARCHAR2(1)
			,TM1_DRKQTY_RSPS_CD 	NUMBER(3)
			,MOV20_WEK_FREQ_ID 		VARCHAR2(1)
			,MOV30_WEK_FREQ_ID 		VARCHAR2(1)
			,WLK30_WEK_FREQ_ID 		VARCHAR2(1)
			)
			ORGANIZATION EXTERNAL
			(
			TYPE oracle_loader
			DEFAULT DIRECTORY GJ
			ACCESS PARAMETERS
			(
			RECORDS DELIMITED BY ''\n''
			CHARACTERSET KO16KSC5601
			FIELDS TERMINATED BY ''|'' OPTIONALLY ENCLOSED BY ''"'' LRTRIM
			MISSING FIELD VALUES ARE NULL
			)
			LOCATION
			(
			''NHID_GJ_'||idx||'.TXT''
			)
			)REJECT LIMIT UNLIMITED');
		end loop;

	for idx in 2002..2013
	loop
		execute immediate(
			'create table NHID_GJ_'||idx||'
			as
			select * from NHID_GJ_'||idx||'_ext');
	end loop;

	for idx in 2002..2013
	loop
		execute immediate(
			'select * from NHID_GJ_'||idx);
	end loop;
end;

--drop table NHID_GY20_T1_2004_ext;
--alter table NHID_GY20_T1_2004 rename to NHID_GY20_T1_2004_ext;
--select * from NHID_GJ_2002;
--select * from NHID_GJ_2013;

/* see the list of tables
--select table_name from user_tables;
*/

