SELECT COUNT(ROWNUM) FROM NHID_JK_2002 WHERE AGE_GROUP=0;

SELECT COUNT(ROWNUM) FROM NHID_JK_2003;
SELECT COUNT(ROWNUM) FROM (SELECT UNIQUE PERSON_ID FROM NHID_JK_2003); -- the same as above line -- all person_id unique

SELECT COUNT(ROWNUM) FROM (
SELECT JK2.STND_Y, JK2.PERSON_ID, JK2.AGE_GROUP,
       JK3.STND_Y, JK3.PERSON_ID, JK3.AGE_GROUP,
       JK4.STND_Y, JK4.PERSON_ID, JK4.AGE_GROUP,
       JK5.STND_Y, JK5.PERSON_ID, JK5.AGE_GROUP,
       JK6.STND_Y, JK6.PERSON_ID, JK6.AGE_GROUP,
       JK7.STND_Y, JK7.PERSON_ID, JK7.AGE_GROUP,
       JK8.STND_Y, JK8.PERSON_ID, JK8.AGE_GROUP,
       JK9.STND_Y, JK9.PERSON_ID, JK9.AGE_GROUP,
       JK10.STND_Y, JK10.PERSON_ID, JK10.AGE_GROUP,
       JK11.STND_Y, JK11.PERSON_ID, JK11.AGE_GROUP,
       JK12.STND_Y, JK12.PERSON_ID, JK12.AGE_GROUP,
       JK13.STND_Y, JK13.PERSON_ID, JK13.AGE_GROUP
    FROM NHID_JK_2002 JK2,
         NHID_JK_2003 JK3,
         NHID_JK_2004 JK4,
         NHID_JK_2005 JK5,
         NHID_JK_2006 JK6,
         NHID_JK_2007 JK7,
         NHID_JK_2008 JK8,
         NHID_JK_2009 JK9,
         NHID_JK_2010 JK10,
         NHID_JK_2011 JK11,
         NHID_JK_2012 JK12,
         NHID_JK_2013 JK13
    WHERE JK2.PERSON_ID = JK3.PERSON_ID AND JK3.PERSON_ID = JK4.PERSON_ID AND JK4.PERSON_ID = JK5.PERSON_ID AND JK5.PERSON_ID = JK6.PERSON_ID AND JK6.PERSON_ID = JK7.PERSON_ID AND JK7.PERSON_ID = JK8.PERSON_ID AND JK8.PERSON_ID = JK9.PERSON_ID AND JK9.PERSON_ID = JK10.PERSON_ID AND JK11.PERSON_ID = JK12.PERSON_ID AND JK12.PERSON_ID = JK13.PERSON_ID AND JK10.PERSON_ID = JK11.PERSON_ID ;
    );