		create table ACTtoRXNORM_EXT
			(CONCEPT_ID_1 NUMBER(10),
			 CONCEPT_ID_1_CONCEPT_CODE VARCHAR2(1000),
			 CONCEPT_ID_1_NAME VARCHAR2(1000),
			 CONCEPT_ID_1_DOMAIN_ID VARCHAR2(1000),
			 CONCEPT_ID_1_VOCABULARY_ID VARCHAR2(1000),
			 CONCEPT_ID_1_CONCEPT_CLASS_ID VARCHAR2(1000),
			 CONCEPT_ID_1_INVALID_REASON VARCHAR2(1000),
			 CONCEPT_ID_1_STANDARD_CONCEPT VARCHAR2(1000),
			 CONCEPT_ID_1_VALID_START_DATE VARCHAR2(10),
			 CONCEPT_ID_1_VALID_END_DATE VARCHAR2(10),
			 CONCEPT_ID_2_CONCEPT_CODE NUMBER(10),
			 CONCEPT_ID_2 NUMBER(10),
			 CONCEPT_ID_2_NAME VARCHAR2(1000),
			 CONCEPT_ID_2_DOMAIN_ID VARCHAR2(1000),
			 CONCEPT_ID_2_VOCABULARY_ID VARCHAR2(1000),
			 CONCEPT_ID_2_CONCEPT_CLASS_ID VARCHAR2(1000),
			 CONCEPT_ID_2_INVALID_REASON VARCHAR2(1000),
			 CONCEPT_ID_2_STANDARD_CONCEPT VARCHAR2(1000),
			 CONCEPT_ID_2_VALID_START_DATE VARCHAR2(10),
			 CONCEPT_ID_2_VALID_END_DATE VARCHAR2(10)
			)
			ORGANIZATION EXTERNAL
			(
			TYPE oracle_loader
			DEFAULT DIRECTORY MAPTABLE
			ACCESS PARAMETERS
			(
			RECORDS DELIMITED BY newline fields
			MISSING FIELD VALUES ARE NULL
			)
			LOCATION
			(
			'ACTtoRXNORM.csv'
			)
			)REJECT LIMIT UNLIMITED;

create table ACTtoRXNORM as select * from ACTtoRXNORM_EXT;

select * from ACTtoRXNORM;

--drop table ACTtoRXNORM_EXT;
--DROP TABLE ACTtoRXNORM;
--alter table NHID_GY20_T1_2004 rename to NHID_GY20_T1_2004_ext;
--select * from NHID_GJ_2002;
--select * from NHID_GJ_2013;

/* see the list of tables
--select table_name from user_tables;
*/

