/*------------------------*/
/*--------1.PERSON--------*/
/*------------------------*/
CREATE TABLE PERSON_EX
(
 person_id						INTEGER		NOT NULL ,
 gender_concept_id				INTEGER		NOT NULL ,
 year_of_birth					INTEGER		NOT NULL ,
 month_of_birth					INTEGER		NULL,
 day_of_birth					INTEGER		NULL,
 birth_datetime					TIMESTAMP WITH TIME ZONE	NULL,
 race_concept_id				INTEGER		NOT NULL,
 ethnicity_concept_id			INTEGER		NOT NULL,
 location_id					INTEGER		NULL,
 provider_id					INTEGER		NULL,
 care_site_id					INTEGER		NULL,
 person_source_value			VARCHAR2(50) NULL,
 gender_source_value			VARCHAR2(50) NULL,
 gender_source_concept_id		INTEGER		NULL,
 race_source_value				VARCHAR2(50) NULL,
 race_source_concept_id			INTEGER		NULL,
 ethnicity_source_value			VARCHAR2(50) NULL,
 ethnicity_source_concept_id	INTEGER		NULL
)
;

CREATE TABLE PERSON_EX_ext
(
PERSON_ID		NUMBER(38),
GENDER_CONCEPT_ID		NUMBER(38),
YEAR_OF_BIRTH		NUMBER(38),
MONTH_OF_BIRTH		NUMBER(38),
DAY_OF_BIRTH		NUMBER(38),
BIRTH_DATETIME		TIMESTAMP(6),
RACE_CONCEPT_ID		NUMBER(38),
ETHNICITY_CONCEPT_ID		NUMBER(38),
LOCATION_ID		NUMBER(38),
PROVIDER_ID		NUMBER(38),
CARE_SITE_ID		NUMBER(38),
PERSON_SOURCE_VALUE		VARCHAR2(50),
GENDER_SOURCE_VALUE		VARCHAR2(50),
GENDER_SOURCE_CONCEPT_ID		NUMBER(38),
RACE_SOURCE_VALUE		VARCHAR2(50),
RACE_SOURCE_CONCEPT_ID		NUMBER(38),
ETHNICITY_SOURCE_VALUE		VARCHAR2(50),
ETHNICITY_SOURCE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
PERSON_ID,
GENDER_CONCEPT_ID,
YEAR_OF_BIRTH,
MONTH_OF_BIRTH,
DAY_OF_BIRTH,
BIRTH_DATETIME,
RACE_CONCEPT_ID,
ETHNICITY_CONCEPT_ID,
LOCATION_ID,
PROVIDER_ID,
CARE_SITE_ID,
PERSON_SOURCE_VALUE		,
GENDER_SOURCE_VALUE		,
GENDER_SOURCE_CONCEPT_ID,
RACE_SOURCE_VALUE		,
RACE_SOURCE_CONCEPT_ID,
ETHNICITY_SOURCE_VALUE		,
ETHNICITY_SOURCE_CONCEPT_ID
 )
)
 LOCATION ('person_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into PERSON_EX
select * from  PERSON_EX_ext;

select * from PERSON_EX ;

/*----------------------------------*/
/*--------2.VISIT OCCURRENCE--------*/
/*----------------------------------*/
CREATE TABLE VISIT_OCCURRENCE_EX
(
 visit_occurrence_id			INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     visit_concept_id				INTEGER			NOT NULL ,
	 visit_start_date				DATE			NOT NULL ,
	 visit_start_datetime				TIMESTAMP WITH TIME ZONE		NULL ,
     visit_end_date					DATE			NOT NULL ,
	 visit_end_datetime					TIMESTAMP WITH TIME ZONE		NULL ,
	 visit_type_concept_id			INTEGER			NOT NULL ,
	 provider_id					INTEGER			NULL,
     care_site_id					INTEGER			NULL,
     visit_source_value				VARCHAR2(50)		NULL,
	 visit_source_concept_id		INTEGER			NULL,
	 admitting_source_concept_id	INTEGER			NULL ,
	 admitting_source_value			VARCHAR2(50)		NULL ,
	 discharge_to_concept_id		INTEGER		NULL ,
	 discharge_to_source_value		VARCHAR2(50)		NULL ,
	 preceding_visit_occurrence_id	INTEGER			NULL
)
;

CREATE TABLE VISIT_OCCURRENCE_EX_ext
(
VISIT_OCCURRENCE_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
VISIT_CONCEPT_ID		NUMBER(38),
VISIT_START_DATE		VARCHAR2(20),
VISIT_START_DATETIME		TIMESTAMP(6) ,
VISIT_END_DATE		VARCHAR2(20),
VISIT_END_DATETIME		TIMESTAMP(6) ,
VISIT_TYPE_CONCEPT_ID		NUMBER(38),
PROVIDER_ID		NUMBER(38),
CARE_SITE_ID		NUMBER(38),
VISIT_SOURCE_VALUE		VARCHAR2(50),
VISIT_SOURCE_CONCEPT_ID		NUMBER(38),
ADMITTING_SOURCE_CONCEPT_ID		NUMBER(38),
ADMITTING_SOURCE_VALUE		VARCHAR2(50),
DISCHARGE_TO_CONCEPT_ID		NUMBER(38),
DISCHARGE_TO_SOURCE_VALUE		VARCHAR2(50),
PRECEDING_VISIT_OCCURRENCE_ID		NUMBER(38)
 )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
VISIT_OCCURRENCE_ID	,
PERSON_ID	,
VISIT_CONCEPT_ID	,
VISIT_START_DATE,
VISIT_START_DATETIME,
VISIT_END_DATE,
VISIT_END_DATETIME,
VISIT_TYPE_CONCEPT_ID	,
PROVIDER_ID	,
CARE_SITE_ID	,
VISIT_SOURCE_VALUE,
VISIT_SOURCE_CONCEPT_ID	,
ADMITTING_SOURCE_CONCEPT_ID	,
ADMITTING_SOURCE_VALUE,
DISCHARGE_TO_CONCEPT_ID	,
DISCHARGE_TO_SOURCE_VALUE,
PRECEDING_VISIT_OCCURRENCE_ID
 )
)
 LOCATION ('VISIT_OCCURRENCE_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into VISIT_OCCURRENCE_EX
select * from  VISIT_OCCURRENCE_EX_ext;

select * from VISIT_OCCURRENCE_EX where rownum<100;

/*---------------------------*/
/*--------3.CARE SITE--------*/
/*---------------------------*/
CREATE TABLE CARE_SITE_EX
(
 care_site_id						INTEGER			NOT NULL ,
 care_site_name						VARCHAR2(255)	NULL ,
 place_of_service_concept_id		INTEGER			NULL ,
 location_id						INTEGER			NULL ,
 care_site_source_value				VARCHAR2(50)		NULL ,
 place_of_service_source_value		VARCHAR2(50)		NULL
)
;

CREATE TABLE CARE_SITE_EX_ext
(
CARE_SITE_ID		NUMBER(38),
CARE_SITE_NAME		VARCHAR2(255),
PLACE_OF_SERVICE_CONCEPT_ID		NUMBER(38),
LOCATION_ID		NUMBER(38),
CARE_SITE_SOURCE_VALUE		VARCHAR2(50),
PLACE_OF_SERVICE_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
CARE_SITE_ID		,
CARE_SITE_NAME,
PLACE_OF_SERVICE_CONCEPT_ID,
LOCATION_ID,
CARE_SITE_SOURCE_VALUE,
PLACE_OF_SERVICE_SOURCE_VALUE
 )
)
 LOCATION ('care_site_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into CARE_SITE_EX
select * from  CARE_SITE_EX_ext;

select * from CARE_SITE_EX where rownum<100;

/*--------------------------*/
/*--------4.PROVIDER--------*/
/*--------------------------*/
CREATE TABLE provider_EX
    (
     provider_id					INTEGER			NOT NULL ,
	 provider_name					VARCHAR2(255)	NULL ,
     NPI							VARCHAR2(20)		NULL ,
     DEA							VARCHAR2(20)		NULL ,
     specialty_concept_id			INTEGER			NULL ,
     care_site_id					INTEGER			NULL ,
	 year_of_birth					INTEGER			NULL ,
	 gender_concept_id				INTEGER			NULL ,
     provider_source_value			VARCHAR2(50)		NULL ,
     specialty_source_value			VARCHAR2(50)		NULL ,
	 specialty_source_concept_id	INTEGER			NULL ,
	 gender_source_value			VARCHAR2(50)		NULL ,
	 gender_source_concept_id		INTEGER			NULL
    )
;

CREATE TABLE PROVIDER_EX_ext
(
PROVIDER_ID		NUMBER(38),
PROVIDER_NAME		VARCHAR2(255),
NPI		VARCHAR2(20),
DEA		VARCHAR2(20),
SPECIALTY_CONCEPT_ID		NUMBER(38),
CARE_SITE_ID		NUMBER(38),
YEAR_OF_BIRTH		NUMBER(38),
GENDER_CONCEPT_ID		NUMBER(38),
PROVIDER_SOURCE_VALUE		VARCHAR2(50),
SPECIALTY_SOURCE_VALUE		VARCHAR2(50),
SPECIALTY_SOURCE_CONCEPT_ID		NUMBER(38),
GENDER_SOURCE_VALUE		VARCHAR2(50),
GENDER_SOURCE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
PROVIDER_ID,
PROVIDER_NAME,
NPI,
DEA,
SPECIALTY_CONCEPT_ID,
CARE_SITE_ID,
YEAR_OF_BIRTH,
GENDER_CONCEPT_ID,
PROVIDER_SOURCE_VALUE,
SPECIALTY_SOURCE_VALUE,
SPECIALTY_SOURCE_CONCEPT_ID,
GENDER_SOURCE_VALUE,
GENDER_SOURCE_CONCEPT_ID
 )
)
 LOCATION ('provider_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into PROVIDER_EX
select * from  PROVIDER_EX_ext;

select * from PROVIDER_EX ;

/*--------------------------*/
/*--------5.SPECIMEN--------*/
/*--------------------------*/
CREATE TABLE SPECIMEN_EX
(
	specimen_id						INTEGER			NOT NULL ,
	 person_id							INTEGER			NOT NULL ,
	 specimen_concept_id				INTEGER			NOT NULL ,
	 specimen_type_concept_id			INTEGER			NOT NULL ,
	 specimen_date						DATE			NOT NULL ,
	 specimen_datetime						TIMESTAMP WITH TIME ZONE		NULL ,
	 quantity							FLOAT			NULL ,
	 unit_concept_id					INTEGER			NULL ,
	 anatomic_site_concept_id			INTEGER			NULL ,
	 disease_status_concept_id			INTEGER			NULL ,
	 specimen_source_id					VARCHAR2(50)		NULL ,
	 specimen_source_value				VARCHAR2(50)		NULL ,
	 unit_source_value					VARCHAR2(50)		NULL ,
	 anatomic_site_source_value			VARCHAR2(50)		NULL ,
	 disease_status_source_value		VARCHAR2(50)		NULL
)
;

CREATE TABLE SPECIMEN_EX_ext
(
SPECIMEN_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
SPECIMEN_CONCEPT_ID		NUMBER(38),
SPECIMEN_TYPE_CONCEPT_ID		NUMBER(38),
SPECIMEN_DATE		VARCHAR2(20),
SPECIMEN_DATETIME		TIMESTAMP(6),
QUANTITY		FLOAT(126),
UNIT_CONCEPT_ID		NUMBER(38),
ANATOMIC_SITE_CONCEPT_ID		NUMBER(38),
DISEASE_STATUS_CONCEPT_ID		NUMBER(38),
SPECIMEN_SOURCE_ID		VARCHAR2(50),
SPECIMEN_SOURCE_VALUE		VARCHAR2(50),
UNIT_SOURCE_VALUE		VARCHAR2(50),
ANATOMIC_SITE_SOURCE_VALUE		VARCHAR2(50),
DISEASE_STATUS_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
SPECIMEN_ID,
PERSON_ID,
SPECIMEN_CONCEPT_ID,
SPECIMEN_TYPE_CONCEPT_ID,
SPECIMEN_DATE,
SPECIMEN_DATETIME,
QUANTITY,
UNIT_CONCEPT_ID,
ANATOMIC_SITE_CONCEPT_ID,
DISEASE_STATUS_CONCEPT_ID,
SPECIMEN_SOURCE_ID,
SPECIMEN_SOURCE_VALUE,
UNIT_SOURCE_VALUE,
ANATOMIC_SITE_SOURCE_VALUE,
DISEASE_STATUS_SOURCE_VALUE
 )
)
 LOCATION ('specimen_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into SPECIMEN_EX
select * from  SPECIMEN_EX_ext;

select * from SPECIMEN_EX where rownum<100;

/*--------------------------*/
/*--------6.LOCATION--------*/
/*--------------------------*/
CREATE TABLE LOCATION_EX
(
	location_id					INTEGER			NOT NULL ,
     address_1						VARCHAR2(50)		NULL ,
     address_2						VARCHAR2(50)		NULL ,
     city							VARCHAR2(50)		NULL ,
     state							CHAR(2)		NULL ,
     zip							VARCHAR2(9)		NULL ,
     county							VARCHAR2(20)		NULL ,
     location_source_value			VARCHAR2(50)		NULL
)
;

CREATE TABLE LOCATION_EX_ext
(
LOCATION_ID		NUMBER(38),
ADDRESS_1		VARCHAR2(50),
ADDRESS_2		VARCHAR2(50),
CITY		VARCHAR2(50),
STATE		CHAR(2),
ZIP		VARCHAR2(9),
COUNTY		VARCHAR2(20),
LOCATION_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
LOCATION_ID,
ADDRESS_1,
ADDRESS_2,
CITY,
STATE,
ZIP,
COUNTY,
LOCATION_SOURCE_VALUE
 )
)
 LOCATION ('location_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into LOCATION_EX
select * from  LOCATION_EX_ext;

select * from LOCATION_EX where rownum<100;

/*-----------------------------*/
/*--------7.OBSERVATION--------*/
/*-----------------------------*/
CREATE TABLE OBSERVATION_EX
(
	observation_id					INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     observation_concept_id			INTEGER			NOT NULL ,
     observation_date				DATE			NOT NULL ,
     observation_datetime				TIMESTAMP WITH TIME ZONE		NULL ,
     observation_type_concept_id	INTEGER			NOT NULL ,
	 value_as_number				FLOAT			NULL ,
     value_as_string				VARCHAR2(60)		NULL ,
     value_as_concept_id			INTEGER			NULL ,
	 qualifier_concept_id			INTEGER			NULL ,
     unit_concept_id				INTEGER			NULL ,
     provider_id					INTEGER			NULL ,
     visit_occurrence_id			INTEGER			NULL ,
     observation_source_value		VARCHAR2(50)		NULL ,
	 observation_source_concept_id	INTEGER			NULL ,
     unit_source_value				VARCHAR2(50)		NULL ,
	 qualifier_source_value			VARCHAR2(50)		NULL
)
;

CREATE TABLE OBSERVATION_EX_ext
(
OBSERVATION_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
OBSERVATION_CONCEPT_ID		NUMBER(38),
OBSERVATION_DATE		VARCHAR2(20),
OBSERVATION_DATETIME		TIMESTAMP(6) ,
OBSERVATION_TYPE_CONCEPT_ID		NUMBER(38),
VALUE_AS_NUMBER		FLOAT(126),
VALUE_AS_STRING		VARCHAR2(60),
VALUE_AS_CONCEPT_ID		NUMBER(38),
QUALIFIER_CONCEPT_ID		NUMBER(38),
UNIT_CONCEPT_ID		NUMBER(38),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
OBSERVATION_SOURCE_VALUE		VARCHAR2(50),
OBSERVATION_SOURCE_CONCEPT_ID		NUMBER(38),
UNIT_SOURCE_VALUE		VARCHAR2(50),
QUALIFIER_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
OBSERVATION_ID,
PERSON_ID,
OBSERVATION_CONCEPT_ID,
OBSERVATION_DATE,
OBSERVATION_DATETIME,
OBSERVATION_TYPE_CONCEPT_ID,
VALUE_AS_NUMBER,
VALUE_AS_STRING,
VALUE_AS_CONCEPT_ID,
QUALIFIER_CONCEPT_ID,
UNIT_CONCEPT_ID,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
OBSERVATION_SOURCE_VALUE,
OBSERVATION_SOURCE_CONCEPT_ID,
UNIT_SOURCE_VALUE,
QUALIFIER_SOURCE_VALUE
 )
)
 LOCATION ('observation_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into OBSERVATION_EX
select * from  OBSERVATION_EX_ext;

select * from OBSERVATION_EX where rownum<100;

/*-----------------------------------*/
/*--------8.PAYER PLAN PERIOD--------*/
/*-----------------------------------*/
CREATE TABLE PAYER_PLAN_PERIOD_EX
    (
     payer_plan_period_id			INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     payer_plan_period_start_date	DATE			NOT NULL ,
     payer_plan_period_end_date		DATE			NOT NULL ,
     payer_source_value				VARCHAR2 (50)	NULL ,
     plan_source_value				VARCHAR2 (50)	NULL ,
     family_source_value			VARCHAR2 (50)	NULL
    )
;

CREATE TABLE PAYER_PLAN_PERIOD_EX_ext
(
PAYER_PLAN_PERIOD_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
PAYER_PLAN_PERIOD_START_DATE	VARCHAR2(20),
PAYER_PLAN_PERIOD_END_DATE	VARCHAR2(20),
PAYER_SOURCE_VALUE		VARCHAR2(50),
PLAN_SOURCE_VALUE		VARCHAR2(50),
FAMILY_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
PAYER_PLAN_PERIOD_ID,
PERSON_ID,
PAYER_PLAN_PERIOD_START_DATE,
PAYER_PLAN_PERIOD_END_DATE,
PAYER_SOURCE_VALUE,
PLAN_SOURCE_VALUE,
FAMILY_SOURCE_VALUE
 )
)
 LOCATION ('payer_plan_period_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into PAYER_PLAN_PERIOD_EX
select * from  PAYER_PLAN_PERIOD_EX_ext;

select * from PAYER_PLAN_PERIOD_EX where rownum<100;

/*-----------------------------*/
/*--------9.MEASUREMENT--------*/
/*-----------------------------*/
CREATE TABLE MEASUREMENT_EX
    (
     measurement_id					INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     measurement_concept_id			INTEGER			NOT NULL ,
     measurement_date				DATE			NOT NULL ,
     measurement_datetime				TIMESTAMP WITH TIME ZONE		NULL ,
	 measurement_type_concept_id	INTEGER			NOT NULL ,
	 operator_concept_id			INTEGER			NULL ,
     value_as_number				FLOAT			NULL ,
     value_as_concept_id			INTEGER			NULL ,
     unit_concept_id				INTEGER			NULL ,
     range_low						FLOAT			NULL ,
     range_high						FLOAT			NULL ,
     provider_id					INTEGER			NULL ,
     visit_occurrence_id			INTEGER			NULL ,
     measurement_source_value		VARCHAR2(50)		NULL ,
	 measurement_source_concept_id	INTEGER			NULL ,
     unit_source_value				VARCHAR2(50)		NULL ,
	 value_source_value				VARCHAR2(50)		NULL
    )
;

CREATE TABLE MEASUREMENT_EX_ext
(
MEASUREMENT_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
MEASUREMENT_CONCEPT_ID		NUMBER(38),
MEASUREMENT_DATE		VARCHAR2(20),
MEASUREMENT_DATETIME		TIMESTAMP(6),
MEASUREMENT_TYPE_CONCEPT_ID		NUMBER(38),
OPERATOR_CONCEPT_ID		NUMBER(38),
VALUE_AS_NUMBER		FLOAT(126),
VALUE_AS_CONCEPT_ID		NUMBER(38),
UNIT_CONCEPT_ID		NUMBER(38),
RANGE_LOW		FLOAT(126),
RANGE_HIGH		FLOAT(126),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
MEASUREMENT_SOURCE_VALUE		VARCHAR2(50),
MEASUREMENT_SOURCE_CONCEPT_ID		NUMBER(38),
UNIT_SOURCE_VALUE		VARCHAR2(50),
VALUE_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
MEASUREMENT_ID,
PERSON_ID,
MEASUREMENT_CONCEPT_ID,
MEASUREMENT_DATE,
MEASUREMENT_DATETIME,
MEASUREMENT_TYPE_CONCEPT_ID,
OPERATOR_CONCEPT_ID,
VALUE_AS_NUMBER,
VALUE_AS_CONCEPT_ID,
UNIT_CONCEPT_ID,
RANGE_LOW,
RANGE_HIGH,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
MEASUREMENT_SOURCE_VALUE,
MEASUREMENT_SOURCE_CONCEPT_ID,
UNIT_SOURCE_VALUE,
VALUE_SOURCE_VALUE
 )
)
 LOCATION ('measurement_occurrence_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into MEASUREMENT_EX
select * from  MEASUREMENT_EX_ext;

select * from MEASUREMENT_EX where rownum<100;

/*---------------------------------------*/
/*--------10.CONDITION OCCURRENCE--------*/
/*---------------------------------------*/
CREATE TABLE CONDITION_OCCURRENCE_EX
    (
     condition_occurrence_id		INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     condition_concept_id			INTEGER			NOT NULL ,
     condition_start_date			DATE			NOT NULL ,
     condition_start_datetime			TIMESTAMP WITH TIME ZONE			NULL ,
     condition_end_date				DATE			NULL ,
     condition_end_datetime				TIMESTAMP WITH TIME ZONE			NULL ,
     condition_type_concept_id		INTEGER			NOT NULL ,
     stop_reason					VARCHAR2(20)		NULL ,
     provider_id					INTEGER			NULL ,
     visit_occurrence_id			INTEGER			NULL ,
     condition_source_value			VARCHAR2(50)		NULL ,
	 condition_source_concept_id	INTEGER			NULL ,
	 condition_status_source_value	VARCHAR2(50)		NULL ,
     condition_status_concept_id	INTEGER			NULL
    )
;

CREATE TABLE CONDITION_OCCURRENCE_EX_ext
(
CONDITION_OCCURRENCE_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
CONDITION_CONCEPT_ID		NUMBER(38),
CONDITION_START_DATE		VARCHAR2(20),
CONDITION_END_DATE		VARCHAR2(20),
CONDITION_TYPE_CONCEPT_ID		NUMBER(38),
STOP_REASON		VARCHAR2(20),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
CONDITION_SOURCE_VALUE		VARCHAR2(50),
CONDITION_SOURCE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
CONDITION_OCCURRENCE_ID,
PERSON_ID,
CONDITION_CONCEPT_ID,
CONDITION_START_DATE,
CONDITION_END_DATE,
CONDITION_TYPE_CONCEPT_ID,
STOP_REASON,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
CONDITION_SOURCE_VALUE,
CONDITION_SOURCE_CONCEPT_ID
 )
)
 LOCATION ('condition_occurrence_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into CONDITION_OCCURRENCE_EX (CONDITION_OCCURRENCE_ID,
									PERSON_ID,
									CONDITION_CONCEPT_ID,
									CONDITION_START_DATE,
									CONDITION_END_DATE,
									CONDITION_TYPE_CONCEPT_ID,
									STOP_REASON,
									PROVIDER_ID,
									VISIT_OCCURRENCE_ID,
									CONDITION_SOURCE_VALUE,
									CONDITION_SOURCE_CONCEPT_ID)
select CONDITION_OCCURRENCE_ID,
		PERSON_ID,
		CONDITION_CONCEPT_ID,
		CONDITION_START_DATE,
		CONDITION_END_DATE,
		CONDITION_TYPE_CONCEPT_ID,
		STOP_REASON,
		PROVIDER_ID,
		VISIT_OCCURRENCE_ID,
		CONDITION_SOURCE_VALUE,
		CONDITION_SOURCE_CONCEPT_ID
from  CONDITION_OCCURRENCE_EX_ext;

select * from CONDITION_OCCURRENCE_EX where rownum<100;

/*------------------------*/
/*--------11.DEATH--------*/
/*------------------------*/
CREATE TABLE DEATH_EX
(
  person_id					INTEGER			NOT NULL ,
  death_date				DATE			NOT NULL ,
  death_datetime			TIMESTAMP WITH TIME ZONE			NULL ,
  death_type_concept_id		INTEGER			NOT NULL ,
  cause_concept_id			INTEGER			NULL ,
  cause_source_value		VARCHAR2(50)		NULL,
  cause_source_concept_id	INTEGER			NULL
)
;

CREATE TABLE DEATH_EX_ext
(
PERSON_ID		NUMBER(38),
DEATH_DATE		VARCHAR2(20),
DEATH_TYPE_CONCEPT_ID		NUMBER(38),
CAUSE_CONCEPT_ID		NUMBER(38),
CAUSE_SOURCE_VALUE		VARCHAR2(50),
CAUSE_SOURCE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
PERSON_ID,
DEATH_DATE,
DEATH_TYPE_CONCEPT_ID,
CAUSE_CONCEPT_ID,
CAUSE_SOURCE_VALUE,
CAUSE_SOURCE_CONCEPT_ID
 )
)
 LOCATION ('death_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into DEATH_EX (PERSON_ID,
						DEATH_DATE,
						DEATH_TYPE_CONCEPT_ID,
						CAUSE_CONCEPT_ID,
						CAUSE_SOURCE_VALUE,
						CAUSE_SOURCE_CONCEPT_ID)
select PERSON_ID,
		DEATH_DATE,
		DEATH_TYPE_CONCEPT_ID,
		CAUSE_CONCEPT_ID,
		CAUSE_SOURCE_VALUE,
		CAUSE_SOURCE_CONCEPT_ID
 from  DEATH_EX_ext;

select * from DEATH_EX where rownum<100;

/*----------------------------------*/
/*--------12.DEVICE EXPOSURE--------*/
/*----------------------------------*/
CREATE TABLE DEVICE_EXPOSURE_EX
(
   device_exposure_id				INTEGER			NOT NULL ,
   person_id						INTEGER			NOT NULL ,
   device_concept_id				INTEGER			NOT NULL ,
   device_exposure_start_date		DATE			NOT NULL ,
   device_exposure_start_datetime	TIMESTAMP WITH TIME ZONE	NULL ,
   device_exposure_end_date			DATE			NULL ,
   device_exposure_end_datetime		TIMESTAMP WITH TIME ZONE	NULL ,
   device_type_concept_id			INTEGER			NOT NULL ,
   unique_device_id					VARCHAR2(50)		NULL ,
   quantity							INTEGER			NULL ,
   provider_id						INTEGER			NULL ,
   visit_occurrence_id				INTEGER			NULL ,
   device_source_value				VARCHAR2(100)	NULL ,
   device_source_concept_id			INTEGER			NULL
)
;
CREATE TABLE DEVICE_EXPOSURE_EX_ext
(
DEVICE_EXPOSURE_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
DEVICE_CONCEPT_ID		NUMBER(38),
DEVICE_EXPOSURE_START_DATE		VARCHAR2(20),
DEVICE_EXPOSURE_END_DATE		VARCHAR2(20),
DEVICE_TYPE_CONCEPT_ID		NUMBER(38),
UNIQUE_DEVICE_ID		VARCHAR2(50),
QUANTITY		NUMBER(38),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
DEVICE_SOURCE_VALUE		VARCHAR2(100),
DEVICE_SOURCE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
DEVICE_EXPOSURE_ID,
PERSON_ID,
DEVICE_CONCEPT_ID,
DEVICE_EXPOSURE_START_DATE,
DEVICE_EXPOSURE_END_DATE,
DEVICE_TYPE_CONCEPT_ID,
UNIQUE_DEVICE_ID,
QUANTITY,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
DEVICE_SOURCE_VALUE,
DEVICE_SOURCE_CONCEPT_ID
 )
)
 LOCATION ('device_exposure_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into DEVICE_EXPOSURE_EX (DEVICE_EXPOSURE_ID,
								PERSON_ID,
								DEVICE_CONCEPT_ID,
								DEVICE_EXPOSURE_START_DATE,
								DEVICE_EXPOSURE_END_DATE,
								DEVICE_TYPE_CONCEPT_ID,
								UNIQUE_DEVICE_ID,
								QUANTITY,
								PROVIDER_ID,
								VISIT_OCCURRENCE_ID,
								DEVICE_SOURCE_VALUE,
								DEVICE_SOURCE_CONCEPT_ID)
select DEVICE_EXPOSURE_ID,
		PERSON_ID,
		DEVICE_CONCEPT_ID,
		DEVICE_EXPOSURE_START_DATE,
		DEVICE_EXPOSURE_END_DATE,
		DEVICE_TYPE_CONCEPT_ID,
		UNIQUE_DEVICE_ID,
		QUANTITY,
		PROVIDER_ID,
		VISIT_OCCURRENCE_ID,
		DEVICE_SOURCE_VALUE,
		DEVICE_SOURCE_CONCEPT_ID
from  DEVICE_EXPOSURE_EX_ext;

select * from DEVICE_EXPOSURE_EX where rownum<100;

/*-------------------------------------*/
/*--------13.OBSERVATION PERIOD--------*/
/*-------------------------------------*/
CREATE TABLE OBSERVATION_PERIOD_EX
(
     observation_period_id				INTEGER		NOT NULL ,
     person_id							INTEGER		NOT NULL ,
     observation_period_start_date		DATE		NOT NULL ,
     observation_period_end_date		DATE		NOT NULL ,
	 period_type_concept_id				INTEGER		NOT NULL
    )
;
CREATE TABLE OBSERVATION_PERIOD_EX_ext
(
OBSERVATION_PERIOD_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
OBSERVATION_PERIOD_START_DATE		VARCHAR2(20),
OBSERVATION_PERIOD_END_DATE		VARCHAR2(20),
PERIOD_TYPE_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
OBSERVATION_PERIOD_ID,
PERSON_ID,
OBSERVATION_PERIOD_START_DATE,
OBSERVATION_PERIOD_END_DATE,
PERIOD_TYPE_CONCEPT_ID
 )
)
 LOCATION ('observation_period_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into OBSERVATION_PERIOD_EX
select * from  OBSERVATION_PERIOD_EX_ext;

select * from OBSERVATION_PERIOD_EX where rownum<100;

/*---------------------------------------*/
/*--------14.PROCEDURE OCCURRENCE--------*/
/*---------------------------------------*/
CREATE TABLE PROCEDURE_OCCURRENCE_EX
(
     procedure_occurrence_id		INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     procedure_concept_id			INTEGER			NOT NULL ,
     procedure_date					DATE			NOT NULL ,
     procedure_datetime					TIMESTAMP WITH TIME ZONE			NULL ,
     procedure_type_concept_id		INTEGER			NOT NULL ,
	 modifier_concept_id			INTEGER			NULL ,
	 quantity						INTEGER			NULL ,
     provider_id					INTEGER			NULL ,
     visit_occurrence_id			INTEGER			NULL ,
     procedure_source_value			VARCHAR2(50)		NULL ,
	 procedure_source_concept_id	INTEGER			NULL ,
	 qualifier_source_value			VARCHAR2(50)		NULL
    )
;
CREATE TABLE PROCEDURE_OCCURRENCE_EX_ext
(
PROCEDURE_OCCURRENCE_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
PROCEDURE_CONCEPT_ID		NUMBER(38),
PROCEDURE_DATE		VARCHAR2(20),
PROCEDURE_TYPE_CONCEPT_ID		NUMBER(38),
MODIFIER_CONCEPT_ID		NUMBER(38),
QUANTITY		NUMBER(38),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
PROCEDURE_SOURCE_VALUE		VARCHAR2(50),
PROCEDURE_SOURCE_CONCEPT_ID		NUMBER(38),
QUALIFIER_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
PROCEDURE_OCCURRENCE_ID,
PERSON_ID,
PROCEDURE_CONCEPT_ID,
PROCEDURE_DATE,
PROCEDURE_TYPE_CONCEPT_ID,
MODIFIER_CONCEPT_ID,
QUANTITY,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
PROCEDURE_SOURCE_VALUE,
PROCEDURE_SOURCE_CONCEPT_ID,
QUALIFIER_SOURCE_VALUE
 )
)
 LOCATION ('procedure_occurrence_1.CSV')
)
REJECT LIMIT UNLIMITED;

insert into PROCEDURE_OCCURRENCE_EX (PROCEDURE_OCCURRENCE_ID,
									PERSON_ID,
									PROCEDURE_CONCEPT_ID,
									PROCEDURE_DATE,
									PROCEDURE_TYPE_CONCEPT_ID,
									MODIFIER_CONCEPT_ID,
									QUANTITY,
									PROVIDER_ID,
									VISIT_OCCURRENCE_ID,
									PROCEDURE_SOURCE_VALUE,
									PROCEDURE_SOURCE_CONCEPT_ID,
									QUALIFIER_SOURCE_VALUE)
select PROCEDURE_OCCURRENCE_ID,
		PERSON_ID,
		PROCEDURE_CONCEPT_ID,
		PROCEDURE_DATE,
		PROCEDURE_TYPE_CONCEPT_ID,
		MODIFIER_CONCEPT_ID,
		QUANTITY,
		PROVIDER_ID,
		VISIT_OCCURRENCE_ID,
		PROCEDURE_SOURCE_VALUE,
		PROCEDURE_SOURCE_CONCEPT_ID,
		QUALIFIER_SOURCE_VALUE
from  PROCEDURE_OCCURRENCE_EX_ext;

select * from PROCEDURE_OCCURRENCE_EX where rownum<100;


--15START FROM HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*--------------------------------*/
/*--------15.DRUG EXPOSURE--------*/
/*--------------------------------*/
CREATE TABLE DRUG_EXPOSURE_EX
(
     drug_exposure_id				INTEGER			NOT NULL ,
     person_id						INTEGER			NOT NULL ,
     drug_concept_id				INTEGER			NOT NULL ,
     drug_exposure_start_date		DATE			NOT NULL ,
     drug_exposure_start_datetime	TIMESTAMP WITH TIME ZONE			NULL ,
     drug_exposure_end_date			DATE			NOT NULL ,
     drug_exposure_end_datetime		TIMESTAMP WITH TIME ZONE			NULL ,
     verbatim_end_date				DATE			NULL ,
	 drug_type_concept_id			INTEGER			NOT NULL ,
     stop_reason					VARCHAR2(20)		NULL ,
     refills						INTEGER			NULL ,
     quantity						FLOAT			NULL ,
     days_supply					INTEGER			NULL ,
     sig							CLOB	NULL ,
	 route_concept_id				INTEGER			NULL ,
	 lot_number						VARCHAR2(50)		NULL ,
     provider_id					INTEGER			NULL ,
     visit_occurrence_id			INTEGER			NULL ,
     drug_source_value				VARCHAR2(50)		NULL ,
	 drug_source_concept_id			INTEGER			NULL ,
	 route_source_value				VARCHAR2(50)		NULL ,
	 dose_unit_source_value			VARCHAR2(50)		NULL
    )
;
CREATE TABLE DRUG_EXPOSURE_EX_ext
(
DRUG_EXPOSURE_ID		NUMBER(38),
PERSON_ID		NUMBER(38),
DRUG_CONCEPT_ID		NUMBER(38),
DRUG_EXPOSURE_START_DATE	VARCHAR2(20),
DRUG_EXPOSURE_END_DATE	VARCHAR2(20),
DRUG_TYPE_CONCEPT_ID		NUMBER(38),
STOP_REASON		VARCHAR2(20),
REFILLS		NUMBER(38),
QUANTITY		FLOAT(126),
DAYS_SUPPLY		NUMBER(38),
SIG		CLOB,
ROUTE_CONCEPT_ID		NUMBER(38),
effective_drug_dose		FLOAT(126),
dose_unit_concept_id 	NUMBER(38),
LOT_NUMBER		VARCHAR2(50),
PROVIDER_ID		NUMBER(38),
VISIT_OCCURRENCE_ID		NUMBER(38),
DRUG_SOURCE_VALUE		VARCHAR2(50),
DRUG_SOURCE_CONCEPT_ID		NUMBER(38),
ROUTE_SOURCE_VALUE		VARCHAR2(50),
DOSE_UNIT_SOURCE_VALUE		VARCHAR2(50) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY EXAMPLE
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 FIELDS TERMINATED BY ','
 MISSING FIELD VALUES ARE NULL
 (
DRUG_EXPOSURE_ID,
PERSON_ID,
DRUG_CONCEPT_ID,
DRUG_EXPOSURE_START_DATE,
DRUG_EXPOSURE_END_DATE,
DRUG_TYPE_CONCEPT_ID,
STOP_REASON,
REFILLS,
QUANTITY,
DAYS_SUPPLY,
SIG,
ROUTE_CONCEPT_ID,
effective_drug_dose,
dose_unit_concept_id,
LOT_NUMBER,
PROVIDER_ID,
VISIT_OCCURRENCE_ID,
DRUG_SOURCE_VALUE,
DRUG_SOURCE_CONCEPT_ID,
ROUTE_SOURCE_VALUE,
DOSE_UNIT_SOURCE_VALUE
 )
)
 LOCATION ('drug_exposure_1.CSV')
)
REJECT LIMIT UNLIMITED;

INSERT INTO DRUG_EXPOSURE_EX (DRUG_EXPOSURE_ID,
								PERSON_ID,
								DRUG_CONCEPT_ID,
								DRUG_EXPOSURE_START_DATE,
								DRUG_EXPOSURE_END_DATE,
								DRUG_TYPE_CONCEPT_ID,
								STOP_REASON,
								REFILLS,
								QUANTITY,
								DAYS_SUPPLY,
								SIG,
								ROUTE_CONCEPT_ID,
								LOT_NUMBER,
								PROVIDER_ID,
								VISIT_OCCURRENCE_ID,
								DRUG_SOURCE_VALUE,
								DRUG_SOURCE_CONCEPT_ID,
								ROUTE_SOURCE_VALUE,
								DOSE_UNIT_SOURCE_VALUE);

		select DRUG_EXPOSURE_ID,
		PERSON_ID,
		DRUG_CONCEPT_ID,
		DRUG_EXPOSURE_START_DATE,
		NVL(DRUG_EXPOSURE_END_DATE,TO_DATE('2099-12-31','YYYY-MM-DD')),
		DRUG_TYPE_CONCEPT_ID,
		STOP_REASON,
		REFILLS,
		QUANTITY,
		DAYS_SUPPLY,
		SIG,
		ROUTE_CONCEPT_ID,
		LOT_NUMBER,
		PROVIDER_ID,
		VISIT_OCCURRENCE_ID,
		DRUG_SOURCE_VALUE,
		DRUG_SOURCE_CONCEPT_ID,
		ROUTE_SOURCE_VALUE,
		DOSE_UNIT_SOURCE_VALUE
FROM DRUG_EXPOSURE_EX_EXT;

select * from DRUG_EXPOSURE_EX WHERE ROWNUM<100 ;

select NVL(DRUG_EXPOSURE_END_DATE,TO_date('9999-12-31','YYYY-MM-DD'))
from DRUG_EXPOSURE_EX_EXT where rownum<10;

select *
  from DRUG_EXPOSURE_EX_EXT;

from DRUG_EXPOSURE_EX_EXT;


