SELECT PERSON_ID,MAX(YEAR_FROM),MIN(YEAR_TO),ROUND((MAX(YEAR_FROM)+MIN(YEAR_TO))/2)
   FROM (
 SELECT  PERSON_ID
        ,STND_Y
	      ,A.AGE_GROUP
				,AGE_FROM
        ,AGE_TO
				,STND_Y-AGE_TO		AS YEAR_FROM
				,STND_Y-AGE_FROM 	AS YEAR_TO
   FROM NHIS_JK A
  INNER JOIN (
        SELECT 0		AGE_GROUP, 0	AGE_FROM , 0   AGE_TO FROM DUAL UNION ALL
				SELECT 1		AGE_GROUP, 1	AGE_FROM , 4   AGE_TO FROM DUAL UNION ALL
				SELECT 2		AGE_GROUP, 5	AGE_FROM , 9   AGE_TO FROM DUAL UNION ALL
				SELECT 3		AGE_GROUP, 10	AGE_FROM , 14  AGE_TO FROM DUAL UNION ALL
				SELECT 4		AGE_GROUP, 15	AGE_FROM , 19  AGE_TO FROM DUAL UNION ALL
				SELECT 5		AGE_GROUP, 20	AGE_FROM , 24  AGE_TO FROM DUAL UNION ALL
				SELECT 6		AGE_GROUP, 25	AGE_FROM , 29  AGE_TO FROM DUAL UNION ALL
				SELECT 7		AGE_GROUP, 30	AGE_FROM , 34  AGE_TO FROM DUAL UNION ALL
				SELECT 8		AGE_GROUP, 35	AGE_FROM , 39  AGE_TO FROM DUAL UNION ALL
				SELECT 9		AGE_GROUP, 40	AGE_FROM , 44  AGE_TO FROM DUAL UNION ALL
				SELECT 10 	AGE_GROUP, 45	AGE_FROM , 49  AGE_TO FROM DUAL UNION ALL
				SELECT 11 	AGE_GROUP, 50	AGE_FROM , 54  AGE_TO FROM DUAL UNION ALL
				SELECT 12 	AGE_GROUP, 55	AGE_FROM , 59  AGE_TO FROM DUAL UNION ALL
				SELECT 13 	AGE_GROUP, 60	AGE_FROM , 64  AGE_TO FROM DUAL UNION ALL
				SELECT 14 	AGE_GROUP, 65	AGE_FROM , 69  AGE_TO FROM DUAL UNION ALL
				SELECT 15 	AGE_GROUP, 70	AGE_FROM , 74  AGE_TO FROM DUAL UNION ALL
				SELECT 16 	AGE_GROUP, 75	AGE_FROM , 79  AGE_TO FROM DUAL UNION ALL
				SELECT 17 	AGE_GROUP, 80	AGE_FROM , 84  AGE_TO FROM DUAL UNION ALL
				SELECT 18 	AGE_GROUP, 85 AGE_FROM , 90  AGE_TO FROM DUAL
				) B ON A.AGE_GROUP=B.AGE_GROUP
		) X
	GROUP BY X.PERSON_ID;
