/*------------------------------------*/
/*--------CONCEPT RELATIONSHIP--------*/
/*------------------------------------*/
desc concept_relationship;

CREATE TABLE CONCEPT_RELATIONSHIP_ext
(
CONCEPT_ID_1     NUMBER(38)   ,
CONCEPT_ID_2     NUMBER(38)   ,
RELATIONSHIP_ID  VARCHAR2(20) ,
VALID_START_DATE VARCHAR2(20) ,
VALID_END_DATE   VARCHAR2(20) ,
INVALID_REASON   VARCHAR2(1) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
CONCEPT_ID_1      ,
CONCEPT_ID_2      ,
RELATIONSHIP_ID   ,
VALID_START_DATE  ,
VALID_END_DATE    ,
INVALID_REASON
 )
)
 LOCATION ('CONCEPT_RELATIONSHIP.csv')
)
REJECT LIMIT UNLIMITED;

insert into CONCEPT_RELATIONSHIP
select * from  CONCEPT_RELATIONSHIP_ext;

select * from CONCEPT_RELATIONSHIP where rownum<100;

/*--------------------------------*/
/*--------CONCEPT ANCESTOR--------*/
/*--------------------------------*/
desc CONCEPT_ANCESTOR;

CREATE TABLE CONCEPT_ANCESTOR_ext
(
	ANCESTOR_CONCEPT_ID			NUMBER(38),
	DESCENDANT_CONCEPT_ID		NUMBER(38),
	MIN_LEVELS_OF_SEPARATION	NUMBER(38),
	MAX_LEVELS_OF_SEPARATION	NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
 	ANCESTOR_CONCEPT_ID	,
	DESCENDANT_CONCEPT_ID,
	MIN_LEVELS_OF_SEPARATION,
	MAX_LEVELS_OF_SEPARATION
 )
)
 LOCATION ('CONCEPT_ANCESTOR.csv')
)
REJECT LIMIT UNLIMITED;

insert into CONCEPT_ANCESTOR
select * from  CONCEPT_ANCESTOR_ext;

select * from CONCEPT_ANCESTOR where rownum<100;

/*-----------------------------*/
/*--------CONCEPT CLASS--------*/
/*-----------------------------*/
desc concept_CLASS;

CREATE TABLE CONCEPT_CLASS_ext
(
  CONCEPT_CLASS_ID      		VARCHAR2(20),
CONCEPT_CLASS_NAME      		VARCHAR2(255),
CONCEPT_CLASS_CONCEPT_ID  	NUMBER(38))
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
 CONCEPT_CLASS_ID,
CONCEPT_CLASS_NAME,
CONCEPT_CLASS_CONCEPT_ID
 )
)
 LOCATION ('CONCEPT_CLASS.csv')
)
REJECT LIMIT UNLIMITED;

insert into CONCEPT_CLASS
select * from  CONCEPT_CLASS_ext;

select * from CONCEPT_CLASS;

/*-------------------------------*/
/*--------CONCEPT SYNONYM--------*/
/*-------------------------------*/
desc concept_SYNONYM;

CREATE TABLE CONCEPT_SYNONYM_ext
(
CONCEPT_ID	NUMBER(38),
CONCEPT_SYNONYM_NAME	VARCHAR2(1000),
LANGUAGE_CONCEPT_ID	NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
 CONCEPT_ID,
CONCEPT_SYNONYM_NAME,
LANGUAGE_CONCEPT_ID
 )
)
 LOCATION ('CONCEPT_SYNONYM.csv')
)
REJECT LIMIT UNLIMITED;

insert into CONCEPT_SYNONYM
select * from  CONCEPT_SYNONYM_ext;

select * from CONCEPT_SYNONYM where rownum<100;

/*----------------------*/
/*--------DOMAIN--------*/
/*----------------------*/
desc DOMAIN;

CREATE TABLE DOMAIN_ext
(
DOMAIN_ID		VARCHAR2(20),
DOMAIN_NAME		VARCHAR2(255),
DOMAIN_CONCEPT_ID		NUMBER(38)	 )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
DOMAIN_ID,
DOMAIN_NAME,
DOMAIN_CONCEPT_ID
 )
)
 LOCATION ('DOMAIN.csv')
)
REJECT LIMIT UNLIMITED;

insert into DOMAIN
select * from  DOMAIN_ext;

select * from DOMAIN where rownum<100;

/*-----------------------------*/
/*--------DRUG STRENGTH--------*/
/*-----------------------------*/
desc DRUG_STRENGTH;

CREATE TABLE DRUG_STRENGTH_ext
(
DRUG_CONCEPT_ID		NUMBER(38),
INGREDIENT_CONCEPT_ID		NUMBER(38),
AMOUNT_VALUE		FLOAT(126),
AMOUNT_UNIT_CONCEPT_ID		NUMBER(38),
NUMERATOR_VALUE		FLOAT(126),
NUMERATOR_UNIT_CONCEPT_ID		NUMBER(38),
DENOMINATOR_VALUE		FLOAT(126),
DENOMINATOR_UNIT_CONCEPT_ID		NUMBER(38),
BOX_SIZE		NUMBER(38),
VALID_START_DATE	VARCHAR2(20),
VALID_END_DATE	VARCHAR2(20),
INVALID_REASON		CHAR(1) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
DRUG_CONCEPT_ID,
INGREDIENT_CONCEPT_ID,
AMOUNT_VALUE,
AMOUNT_UNIT_CONCEPT_ID,
NUMERATOR_VALUE,
NUMERATOR_UNIT_CONCEPT_ID,
DENOMINATOR_VALUE,
DENOMINATOR_UNIT_CONCEPT_ID,
BOX_SIZE,
VALID_START_DATE,
VALID_END_DATE,
INVALID_REASON
 )
)
 LOCATION ('DRUG_STRENGTH.csv')
)
REJECT LIMIT UNLIMITED;

insert into DRUG_STRENGTH
select * from  DRUG_STRENGTH_ext;

select * from DRUG_STRENGTH where rownum<100;

/*----------------------------*/
/*--------RELATIONSHIP--------*/
/*----------------------------*/
desc RELATIONSHIP;

CREATE TABLE RELATIONSHIP_ext
(
RELATIONSHIP_ID		VARCHAR2(20),
RELATIONSHIP_NAME		VARCHAR2(255),
IS_HIERARCHICAL		CHAR(1),
DEFINES_ANCESTRY		CHAR(1),
REVERSE_RELATIONSHIP_ID		VARCHAR2(20),
RELATIONSHIP_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
RELATIONSHIP_ID		,
RELATIONSHIP_NAME	,
IS_HIERARCHICAL		,
DEFINES_ANCESTRY	,
REVERSE_RELATIONSHIP_ID	,
RELATIONSHIP_CONCEPT_ID
)
)
 LOCATION ('RELATIONSHIP.csv')
)
REJECT LIMIT UNLIMITED;

insert into RELATIONSHIP
select * from  RELATIONSHIP_ext;

select * from RELATIONSHIP;

/*--------------------------*/
/*--------VOCABULARY--------*/
/*--------------------------*/
desc VOCABULARY;

CREATE TABLE VOCABULARY_ext
(
VOCABULARY_ID		VARCHAR2(20),
VOCABULARY_NAME		VARCHAR2(255),
VOCABULARY_REFERENCE		VARCHAR2(255),
VOCABULARY_VERSION		VARCHAR2(255),
VOCABULARY_CONCEPT_ID		NUMBER(38) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
VOCABULARY_ID		,
VOCABULARY_NAME		,
VOCABULARY_REFERENCE,
VOCABULARY_VERSION	,
VOCABULARY_CONCEPT_ID
 )
)
 LOCATION ('VOCABULARY.csv')
)
REJECT LIMIT UNLIMITED;

insert into VOCABULARY
select * from  VOCABULARY_ext;

select * from VOCABULARY;

/*-----------------------*/
/*--------CONCEPT--------*/
/*-----------------------*/
desc concept;

CREATE TABLE CONCEPT_ext
(
CONCEPT_ID		NUMBER(38),
CONCEPT_NAME	VARCHAR2(255),
DOMAIN_ID		VARCHAR2(20),
VOCABULARY_ID	VARCHAR2(20),
CONCEPT_CLASS_ID		VARCHAR2(20),
STANDARD_CONCEPT		VARCHAR2(1),
CONCEPT_CODE		VARCHAR2(50),
VALID_START_DATE	VARCHAR2(20),
VALID_END_DATE	VARCHAR2(20),
INVALID_REASON		VARCHAR2(1) )
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
 DEFAULT DIRECTORY CONCEPT_DIR
ACCESS PARAMETERS
(RECORDS DELIMITED BY '\n'
 fields terminated by '\t'
 MISSING FIELD VALUES ARE NULL
 (
CONCEPT_ID		,
CONCEPT_NAME	,
DOMAIN_ID		,
VOCABULARY_ID	,
CONCEPT_CLASS_ID,
STANDARD_CONCEPT,
CONCEPT_CODE	,
VALID_START_DATE,
VALID_END_DATE	,
INVALID_REASON
 )
)
 LOCATION ('CONCEPT.csv')
)
REJECT LIMIT UNLIMITED;

insert into CONCEPT
select * from  CONCEPT_ext;

select * from CONCEPT where rownum<100;
