create table NHIS_JK as
SELECT * FROM NHID_JK_2002 UNION ALL
SELECT * FROM NHID_JK_2003 UNION ALL
SELECT * FROM NHID_JK_2004 UNION ALL
SELECT * FROM NHID_JK_2005 UNION ALL
SELECT * FROM NHID_JK_2006 UNION ALL
SELECT * FROM NHID_JK_2007 UNION ALL
SELECT * FROM NHID_JK_2008 UNION ALL
SELECT * FROM NHID_JK_2009 UNION ALL
SELECT * FROM NHID_JK_2010 UNION ALL
SELECT * FROM NHID_JK_2011 UNION ALL
SELECT * FROM NHID_JK_2012 UNION ALL
SELECT * FROM NHID_JK_2013 ;

select /*+parallel(8)*/ count(*) from NHIS_JK;

grant select on NHIS_JK TO CDM_ONE_MIL;

